- name: variables
  hosts: local
  connection: local
  tasks:

- name: Print the variables
  ansible.builtin.debug:
    msg: "Course is Devops with Aws ,Duration is 120 hours,Trainer by Siva Kumar reddy Sir"
