- name: variables
  hosts: local
  connection: local

  vars: # play level Variables
    COURSE: Devops with aws
    DURATION: 120 hours
    TRAINNER: SivaKuamr

  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "Course is {{COURSE}} ,Duration is {{DURATION}} ,Trainner is {{TRAINNER}}"
