- name: variables
  hosts: local
  connection: local
  vars: # play level variables ,global variables
    COURSE: "Devops with siva"
    DURATION: 120HRS
    TRAINNER: SivaKuamr

  tasks:
    - name: print the Variables
      vars: # task level varibles ,accessble only with in the task.Task variables  can override play level variables.
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainner is {{TRAINNER}}"

    - name: Print the variables1
      ansible.builtin.debug:
        msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainner is {{TRAINNER}}"
