- name: variables from files
  hosts: local
  connection: local
  tasks:
    - name: print Course Information
      ansible.builtin.debug:
        msg: " Course is{{ COURSE }},Duration is {{ DURATION }}, Trainner is {{TRAINNER}} "
