- name: filters
  hosts: local
  connection: local
  tasks:
    - name: handle undefined variable
      ansible.builtin.debug:
        msg: "Hello {{Person | default ('Ramesh')}}"

    - name: convert string to list
      vars:
        fruits: "apple,banana,orange"
      ansible.builtin.debug:
        msg: "fruits are: {{fruits | split (',') }}"

    - name: convert into list
      vars:
        course:
          name: ansible
          duration: "120 hrs"
          trainer: Sivakumar
      ansible.builtin.debug:
        msg: "course info : {{ course | dict2items }}"

    - name: list into map
      vars:
        course:
          - { "key": "name", "value": "ansible" }
          - { "key": "duration", "value": "120 hrs" }
          - { "key": "trainer", "value": "Sivakumar" }
      ansible.builtin.debug:
        msg: "course info :{{ course | items2dict }}"

    - name: converts upper to lower
      vars:
        name: "RaHUL KoMMAVARAPu "
      ansible.builtin.debug:
        msg: "hello {{ name | lower }}"

    - name: Convert Lower to upper
      vars:
        name: "rahul Kommavarapu 225"
      ansible.builtin.debug:
        msg: "hello {{ name | upper}}"

    - name: Convert Min to Max of given Numbers
      vars:
        Numbers: [1, 3, 5, 25, 30, 45, 75, 100, 125, 300, 1050, 2050, 5232]
      ansible.builtin.debug:
        msg: "Max is {{ Numbers | max }} ,Min is {{Numbers | min}}"

    - name: Convert Min to Max of the Given Numbers
      vars:
        Numbers: [1, 3, 5, 10, 15, 25, 50, 70, 100, 1050, 2050, 2030, 5230]
      ansible.builtin.debug:
        msg: "Max is {{Numbers|max}},Min is {{Numbers|min}}"
