- name: create ec2 and r53 records
  connection: local
  hosts: local

  vars:
    subnet_id: subnet-0203d08659f98f10f
    sg_id: sg-00909238519d1b46e
    ami_id: ami-0220d79f3f480ecf5
    instance_type: t3.micro
    instances:
      - mysql1
      - backend1
      - frontend1

  tasks:
    - name: Install Aws Python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        region: us-east-1
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: print ec2_info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"

    - name: print private ip addressess
      ansible.builtin.debug:
        msg: "{{ item.instances[0].private_ip_address }"
      loop: "{{ ec2_info.results }}"
