172.31.17.165


[web]
172.31.17.165

[local]
localhost


[web]
100.53.10.108 COURSE="Devops with aws" TRAINER="Siva Sir" DURATION="120 HRS" ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost COURSE="Ansible" TRAINER="Siva Sir" DURATION="12 HRS"




[local:vars]
COURSE = Devops with Aws
TRAINER = Siva Sir
DURATION = 120 HRS

